version: '3.9'
services:
  m1:
    container_name: m1
    build:
      context: ./m1
    volumes:
      - "./m1/nginx.conf:/etc/nginx/nginx.conf"
    ports:
      - "80:80"
    networks:
      - "internal"
  m2:
    container_name: m2
    build:
      context: ./m2
    networks:
      - "internal"
    expose:
      - "80"
      - "8880"
networks:
  internal:
    name: internal_network
